# Generated by Django 6.0.2 on 2026-03-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_alter_students_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main.course'),
        ),
    ]
